export interface UploadedProductImage {
  storagePath: string;
  contentType: string;
  sizeBytes: number;
}

/**
 * Port for product image bytes in Firebase Storage. The storage path is
 * always generated by the implementation from `productId`/`imageId` —
 * callers never supply or influence the path, which is what keeps a
 * caller from ever writing to an arbitrary Storage location. Firestore
 * only ever stores the resulting metadata (`ProductImage`), never image
 * bytes or a long-lived public URL — see README's Image storage design.
 */
export interface ProductImageStoragePort {
  upload(productId: string, imageId: string, contentType: string, bytes: Uint8Array): Promise<UploadedProductImage>;
  delete(storagePath: string): Promise<void>;
  /**
   * A Firebase Storage "download token" URL (`?alt=media&token=...`), not a
   * cryptographically signed GCS URL — see
   * `infrastructure/firebase/product-image-storage.ts`'s doc comment for
   * why, including the tradeoff (it doesn't expire on its own) this
   * implies for admin-only product photography.
   */
  getDownloadUrl(storagePath: string): Promise<string>;
}
